# Generated by Django 3.0.3 on 2020-02-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='update_interval',
            field=models.IntegerField(default=59),
        ),
    ]
