# Generated by Django 3.0.3 on 2020-02-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20200211_0810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveFeeds',
        ),
    ]
