# Generated by Django 3.0.3 on 2020-02-21 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Feed')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Group')),
            ],
        ),
    ]
