# Generated by Django 3.0.3 on 2020-02-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_groupfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
