# Generated by Django 3.0.3 on 2020-02-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_auto_20200225_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='feeds',
            field=models.ManyToManyField(related_name='groups', to='feeds.Feed'),
        ),
    ]
